name = "nstoneregistry"
uuid = "b1f20ac8-61bc-48dc-96ef-46caab193ef0"
repo = "https://github.com/nstone8/nstoneregistry"

[packages]
032a2897-498d-4ece-9283-114705a306b4 = { name = "Chinet", path = "C/Chinet" }
5988455b-e7cf-4aac-8dac-baf68a99dbc5 = { name = "QuantStudio", path = "Q/QuantStudio" }
9995961a-b609-4a7c-a027-532616047065 = { name = "CupaJo", path = "C/CupaJo" }
9f67d30b-7d66-4ece-951a-d199622dd275 = { name = "PointDensityPlots", path = "P/PointDensityPlots" }
a5253c47-3b47-401b-8203-180358aa4e2a = { name = "Delta2", path = "D/Delta2" }
d7e13037-544e-446f-97a1-240955fde5ba = { name = "Recluse", path = "R/Recluse" }
