name = "nstoneregistry"
uuid = "b1f20ac8-61bc-48dc-96ef-46caab193ef0"
repo = "http://github.com/nstone8/nstoneregistry"

[packages]
a5253c47-3b47-401b-8203-180358aa4e2a = { name = "Delta2", path = "D/Delta2" }
