name = "nstoneregistry"
uuid = "b1f20ac8-61bc-48dc-96ef-46caab193ef0"
repo = "https://github.com/nstone8/nstoneregistry"

[packages]
032a2897-498d-4ece-9283-114705a306b4 = { name = "Chinet", path = "C/Chinet" }
075f01f5-5a08-42fe-8034-8ba17c561f6c = { name = "Tessen", path = "T/Tessen" }
12514ac0-2501-4d25-a658-60c223cc758c = { name = "Delica", path = "D/Delica" }
21363b03-61ef-4d89-813f-80ecd0f21085 = { name = "BlinkaBoards", path = "B/BlinkaBoards" }
5988455b-e7cf-4aac-8dac-baf68a99dbc5 = { name = "QuantStudio", path = "Q/QuantStudio" }
69ae5839-fd2b-44f9-9ab5-9d3f4e3a022f = { name = "Toast", path = "T/Toast" }
85469bc7-e4c2-476b-92ae-566ea23def65 = { name = "Pancake", path = "P/Pancake" }
8b92ad99-622a-4a49-8522-837eeba52978 = { name = "Ahmes", path = "A/Ahmes" }
932adbb0-91d4-4af7-8e1a-09270b47ecba = { name = "Strudel", path = "S/Strudel" }
97b91fb3-a4d2-4288-be57-92bc2da75bbe = { name = "Seumouse", path = "S/Seumouse" }
9995961a-b609-4a7c-a027-532616047065 = { name = "CupaJo", path = "C/CupaJo" }
9f67d30b-7d66-4ece-951a-d199622dd275 = { name = "PointDensityPlots", path = "P/PointDensityPlots" }
a5253c47-3b47-401b-8203-180358aa4e2a = { name = "Delta2", path = "D/Delta2" }
afce657e-2d8e-41fb-8ae7-e8fa2da28d11 = { name = "StandardCurves", path = "S/StandardCurves" }
d7e13037-544e-446f-97a1-240955fde5ba = { name = "Recluse", path = "R/Recluse" }
e7f9bf38-9811-4749-971f-6614621a1be4 = { name = "Logicle", path = "L/Logicle" }
f62dbe71-e6a6-4df2-9a5f-437c1dc4c8cd = { name = "Waffle", path = "W/Waffle" }
