name = "nstoneregistry"
uuid = "b1f20ac8-61bc-48dc-96ef-46caab193ef0"
repo = "https://github.com/nstone8/nstoneregistry"

[packages]
032a2897-498d-4ece-9283-114705a306b4 = { name = "Chinet", path = "C/Chinet" }
5988455b-e7cf-4aac-8dac-baf68a99dbc5 = { name = "QuantStudio", path = "Q/QuantStudio" }
a5253c47-3b47-401b-8203-180358aa4e2a = { name = "Delta2", path = "D/Delta2" }
